services:
  db:
    image: postgres:15
    container_name: srs_postgres
    restart: always
    environment:
      POSTGRES_USER: superfood_admin
      POSTGRES_PASSWORD: superfood_password
      POSTGRES_DB: srs_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d # Runs schema.sql and functions.sql on first startup

volumes:
  postgres_data:
